// joke taken from the gta wikia when it described nyc.gci
var EveryLineIsAPhysic;
(function (EveryLineIsAPhysic) {
    function get(needle) {
        const car = list[needle];
        if (!car)
            console.warn(`Can\'t get eliap for car ${needle}`);
        return car || null;
    }
    EveryLineIsAPhysic.get = get;
    function getList() {
        return list;
    }
    EveryLineIsAPhysic.getList = getList;
    const list = {
        'Romero': {
            model: 0,
            turbo: 0,
            value: 50,
            pad: 0,
            mass: 16.5,
            front_drive_bias: 1,
            front_mass_bias: 0.5,
            brake_friction: 1.75,
            turn_in: 0.145,
            turn_ratio: 0.45,
            rear_end_stability: 1.25,
            handbrake_slide_value: 0.18,
            thrust: 0.152,
            max_speed: 0.245,
            anti_strength: 1,
            skid_threshhold: 0.065,
            gear1_multiplier: 0.55,
            gear2_multiplier: 0.68,
            gear3_multiplier: 1,
            gear2_speed: 0.107,
            gear3_speed: 0.165,
            meta: { w: 62, h: 64 }
        },
        'Wellard': {
            model: 1,
            turbo: 0,
            value: 50,
            pad: 0,
            mass: 14.5,
            front_drive_bias: 1,
            front_mass_bias: 0.55,
            brake_friction: 2,
            turn_in: 0.65,
            turn_ratio: 0.35,
            rear_end_stability: 1.5,
            handbrake_slide_value: 0.25,
            thrust: 0.22,
            max_speed: 0.38,
            anti_strength: 1,
            skid_threshhold: 0.139,
            gear1_multiplier: 0.5,
            gear2_multiplier: 0.65,
            gear3_multiplier: 1,
            gear2_speed: 0.125,
            gear3_speed: 0.228,
            meta: { w: 44, h: 64 }
        },
        'Aniston BD4': {
            model: 2,
            turbo: 0,
            value: 50,
            pad: 0,
            mass: 14.5,
            front_drive_bias: 0.6,
            front_mass_bias: 0.5,
            brake_friction: 1.75,
            turn_in: 0.145,
            turn_ratio: 0.45,
            rear_end_stability: 1.25,
            handbrake_slide_value: 0.18,
            thrust: 0.146,
            max_speed: 0.3,
            anti_strength: 1,
            skid_threshhold: 0.085,
            gear1_multiplier: 0.55,
            gear2_multiplier: 0.725,
            gear3_multiplier: 1,
            gear2_speed: 0.11,
            gear3_speed: 0.175,
            meta: { w: 62, h: 64 }
        },
        'Pacifier': {
            model: 3,
            turbo: 0,
            value: 30,
            pad: 0,
            mass: 27,
            front_drive_bias: 0.5,
            front_mass_bias: 0.6,
            brake_friction: 0.9,
            turn_in: 0.25,
            turn_ratio: 0.75,
            rear_end_stability: 1.8,
            handbrake_slide_value: 0.15,
            thrust: 0.225,
            max_speed: 0.247,
            anti_strength: 0.5,
            skid_threshhold: 0.1,
            gear1_multiplier: 0.55,
            gear2_multiplier: 0.8,
            gear3_multiplier: 1,
            gear2_speed: 0.103,
            gear3_speed: 0.192,
            meta: { w: 50, h: 98 }
        },
        'G4 Bank Van': {
            model: 4,
            turbo: 0,
            value: 25,
            pad: 0,
            mass: 24,
            front_drive_bias: 0.5,
            front_mass_bias: 0.5,
            brake_friction: 1.5,
            turn_in: 0.5,
            turn_ratio: 0.4,
            rear_end_stability: 2,
            handbrake_slide_value: 0.75,
            thrust: 0.17,
            max_speed: 0.186,
            anti_strength: 0.5,
            skid_threshhold: 0.075,
            gear1_multiplier: 0.55,
            gear2_multiplier: 0.675,
            gear3_multiplier: 1,
            gear2_speed: 0.081,
            gear3_speed: 0.13,
            meta: { w: 60, h: 104 }
        },
        'Beamer': {
            model: 5,
            turbo: 1,
            value: 40,
            pad: 0,
            mass: 16,
            front_drive_bias: 1,
            front_mass_bias: 0.6,
            brake_friction: 3,
            turn_in: 0.75,
            turn_ratio: 0.4,
            rear_end_stability: 2,
            handbrake_slide_value: 0.5,
            thrust: 0.15,
            max_speed: 0.385,
            anti_strength: 1,
            skid_threshhold: 0.14,
            gear1_multiplier: 0.575,
            gear2_multiplier: 0.75,
            gear3_multiplier: 1,
            gear2_speed: 0.185,
            gear3_speed: 0.275,
            meta: { w: 62, h: 64 }
        },
        'Box Car': {
            model: 6,
            turbo: 0,
            value: 200,
            pad: 0,
            mass: 10,
            front_drive_bias: 0,
            front_mass_bias: 0.5,
            brake_friction: 0.9,
            turn_in: 0.1,
            turn_ratio: 0.9,
            rear_end_stability: 2,
            handbrake_slide_value: 0.2,
            thrust: 0.143,
            max_speed: 0.95,
            anti_strength: 1,
            skid_threshhold: 0.139,
            gear1_multiplier: 0.6,
            gear2_multiplier: 0.8,
            gear3_multiplier: 1,
            gear2_speed: 0.152,
            gear3_speed: 0.228,
            meta: { w: 42, h: 128 }
        },
        'Box Truck': {
            model: 7,
            turbo: 0,
            value: 90,
            pad: 0,
            mass: 28,
            front_drive_bias: 0.5,
            front_mass_bias: 0.7,
            brake_friction: 2,
            turn_in: 0.25,
            turn_ratio: 0.65,
            rear_end_stability: 2.5,
            handbrake_slide_value: 0.45,
            thrust: 0.185,
            max_speed: 0.175,
            anti_strength: 0.75,
            skid_threshhold: 0.065,
            gear1_multiplier: 0.545,
            gear2_multiplier: 0.675,
            gear3_multiplier: 1,
            gear2_speed: 0.088,
            gear3_speed: 0.114,
            meta: { w: 52, h: 128 }
        },
        'Bug': {
            model: 8,
            turbo: 0,
            value: 10,
            pad: 0,
            mass: 6.3,
            front_drive_bias: 1,
            front_mass_bias: 0.45,
            brake_friction: 1.265,
            turn_in: 0.3,
            turn_ratio: 0.175,
            rear_end_stability: 1.5,
            handbrake_slide_value: 0.65,
            thrust: 0.095,
            max_speed: 0.235,
            anti_strength: 1,
            skid_threshhold: 0.05,
            gear1_multiplier: 0.55,
            gear2_multiplier: 0.625,
            gear3_multiplier: 1,
            gear2_speed: 0.125,
            gear3_speed: 0.152,
            meta: { w: 50, h: 52 }
        },
        'Bulwark': {
            model_corrected: 9,
            model: 10,
            turbo: 0,
            value: 50,
            pad: 0,
            mass: 17,
            front_drive_bias: 1,
            front_mass_bias: 0.5,
            brake_friction: 2,
            turn_in: 0.14,
            turn_ratio: 0.45,
            rear_end_stability: 1.5,
            handbrake_slide_value: 0.35,
            thrust: 0.185,
            max_speed: 0.307,
            anti_strength: 0.8,
            skid_threshhold: 0.075,
            gear1_multiplier: 0.65,
            gear2_multiplier: 0.8,
            gear3_multiplier: 1,
            gear2_speed: 0.155,
            gear3_speed: 0.225,
            meta: { w: 64, h: 64 }
        },
        'Bus': {
            model_corrected: 10,
            model: 11,
            turbo: 0,
            value: 60,
            pad: 0,
            mass: 30,
            front_drive_bias: 0.5,
            front_mass_bias: 0.5,
            brake_friction: 2,
            turn_in: 0.25,
            turn_ratio: 0.65,
            rear_end_stability: 2.5,
            handbrake_slide_value: 0.75,
            thrust: 0.235,
            max_speed: 0.215,
            anti_strength: 0.75,
            skid_threshhold: 0.085,
            gear1_multiplier: 0.55,
            gear2_multiplier: 0.75,
            gear3_multiplier: 1,
            gear2_speed: 0.1,
            gear3_speed: 0.161,
            meta: { w: 52, h: 128 }
        },
        'Cop Car': {
            model_corrected: 11,
            model: 12,
            turbo: 1,
            value: 60,
            pad: 0,
            mass: 14.5,
            front_drive_bias: 1,
            front_mass_bias: 0.5,
            brake_friction: 2,
            turn_in: 0.433,
            turn_ratio: 0.4,
            rear_end_stability: 1.25,
            handbrake_slide_value: 0.4,
            thrust: 0.15,
            max_speed: 0.415,
            anti_strength: 1,
            skid_threshhold: 0.115,
            gear1_multiplier: 0.55,
            gear2_multiplier: 0.68,
            gear3_multiplier: 1,
            gear2_speed: 0.18,
            gear3_speed: 0.29,
            meta: { w: 58, h: 64 }
        },
        'Minx': {
            model_corrected: 12,
            model: 13,
            turbo: 0,
            value: 50,
            pad: 0,
            mass: 14.5,
            front_drive_bias: 0.75,
            front_mass_bias: 0.5,
            brake_friction: 1.75,
            turn_in: 0.145,
            turn_ratio: 0.45,
            rear_end_stability: 1.25,
            handbrake_slide_value: 0.18,
            thrust: 0.14,
            max_speed: 0.24,
            anti_strength: 1,
            skid_threshhold: 0.085,
            gear1_multiplier: 0.55,
            gear2_multiplier: 0.68,
            gear3_multiplier: 1,
            gear2_speed: 0.12,
            gear3_speed: 0.166,
            meta: { w: 58, h: 58 }
        },
        'Eddy': {
            model_corrected: 13,
            model: 14,
            turbo: 0,
            value: 50,
            pad: 0,
            mass: 15,
            front_drive_bias: 1,
            front_mass_bias: 0.5,
            brake_friction: 2,
            turn_in: 0.14,
            turn_ratio: 0.4,
            rear_end_stability: 1.2,
            handbrake_slide_value: 0.35,
            thrust: 0.165,
            max_speed: 0.3,
            anti_strength: 0.8,
            skid_threshhold: 0.085,
            gear1_multiplier: 0.55,
            gear2_multiplier: 0.7,
            gear3_multiplier: 1,
            gear2_speed: 0.12,
            gear3_speed: 0.197,
            meta: { w: 54, h: 62 }
        },
        'Panto': {
            model_corrected: 14,
            model: 16,
            turbo: 0,
            value: 10,
            pad: 0,
            mass: 7,
            front_drive_bias: 1,
            front_mass_bias: 0.5,
            brake_friction: 1.5,
            turn_in: 0.25,
            turn_ratio: 0.3,
            rear_end_stability: 1,
            handbrake_slide_value: 0.2,
            thrust: 0.058,
            max_speed: 0.165,
            anti_strength: 1.25,
            skid_threshhold: 0.04,
            gear1_multiplier: 0.55,
            gear2_multiplier: 0.75,
            gear3_multiplier: 1,
            gear2_speed: 0.082,
            gear3_speed: 0.12,
            meta: { w: 62, h: 56 }
        },
        'Fire Truck': {
            model_corrected: 15,
            model: 17,
            turbo: 0,
            value: 60,
            pad: 0,
            mass: 32,
            front_drive_bias: 0.7,
            front_mass_bias: 0.46,
            brake_friction: 2.7,
            turn_in: 0.85,
            turn_ratio: 0.75,
            rear_end_stability: 0.55,
            handbrake_slide_value: 0.2,
            thrust: 0.233,
            max_speed: 0.255,
            anti_strength: 1,
            skid_threshhold: 0.15,
            gear1_multiplier: 0.575,
            gear2_multiplier: 0.775,
            gear3_multiplier: 1,
            gear2_speed: 0.124,
            gear3_speed: 0.19,
            meta: { w: 58, h: 124 }
        },
        'Shark': {
            model_corrected: 16,
            model: 18,
            turbo: 0,
            value: 50,
            pad: 0,
            mass: 17,
            front_drive_bias: 1,
            front_mass_bias: 0.75,
            brake_friction: 1.5,
            turn_in: 0.65,
            turn_ratio: 0.65,
            rear_end_stability: 1,
            handbrake_slide_value: 0.3,
            thrust: 0.23,
            max_speed: 0.36,
            anti_strength: 1,
            skid_threshhold: 0.1,
            gear1_multiplier: 0.5,
            gear2_multiplier: 0.6,
            gear3_multiplier: 1,
            gear2_speed: 0.125,
            gear3_speed: 0.22,
            meta: { w: 54, h: 64 }
        },
        'GT-A1': {
            model_corrected: 17,
            model: 19,
            turbo: 1,
            value: 60,
            pad: 0,
            mass: 14.5,
            front_drive_bias: 0.5,
            front_mass_bias: 0.5,
            brake_friction: 1.75,
            turn_in: 0.4,
            turn_ratio: 0.35,
            rear_end_stability: 1.25,
            handbrake_slide_value: 0.4,
            thrust: 0.175,
            max_speed: 0.45,
            anti_strength: 1,
            skid_threshhold: 0.115,
            gear1_multiplier: 0.55,
            gear2_multiplier: 0.725,
            gear3_multiplier: 1,
            gear2_speed: 0.225,
            gear3_speed: 0.35,
            meta: { w: 54, h: 64 }
        },
        'Garbage Truck': {
            model_corrected: 18,
            model: 21,
            turbo: 0,
            value: 40,
            pad: 0,
            mass: 28,
            front_drive_bias: 0.5,
            front_mass_bias: 0.3,
            brake_friction: 2.5,
            turn_in: 0.25,
            turn_ratio: 0.55,
            rear_end_stability: 2,
            handbrake_slide_value: 0.35,
            thrust: 0.155,
            max_speed: 0.162,
            anti_strength: 1,
            skid_threshhold: 0.075,
            gear1_multiplier: 0.65,
            gear2_multiplier: 0.75,
            gear3_multiplier: 1,
            gear2_speed: 0.085,
            gear3_speed: 0.12,
            meta: { w: 52, h: 86 }
        },
        'Armed Land Roamer': {
            model_corrected: 24,
            model: 22,
            turbo: 0,
            value: 30,
            pad: 0,
            mass: 12,
            front_drive_bias: 0.5,
            front_mass_bias: 0.6,
            brake_friction: 1.75,
            turn_in: 0.55,
            turn_ratio: 0.35,
            rear_end_stability: 1.3,
            handbrake_slide_value: 0.175,
            thrust: 0.13,
            max_speed: 0.24,
            anti_strength: 1,
            skid_threshhold: 0.115,
            gear1_multiplier: 0.55,
            gear2_multiplier: 0.6,
            gear3_multiplier: 1,
            gear2_speed: 0.12,
            gear3_speed: 0.152,
            meta: { w: 42, h: 48 }
        },
        'Hot Dog Van': {
            model_corrected: 20,
            model: 23,
            turbo: 0,
            value: 30,
            pad: 0,
            mass: 24,
            front_drive_bias: 0.5,
            front_mass_bias: 0.3,
            brake_friction: 2,
            turn_in: 0.45,
            turn_ratio: 0.6,
            rear_end_stability: 1.15,
            handbrake_slide_value: 0.2,
            thrust: 0.188,
            max_speed: 0.241,
            anti_strength: 1,
            skid_threshhold: 0.07,
            gear1_multiplier: 0.55,
            gear2_multiplier: 0.63,
            gear3_multiplier: 1,
            gear2_speed: 0.094,
            gear3_speed: 0.146,
            meta: { w: 58, h: 88 }
        },
        'Ice-Cream Van': {
            model_corrected: 21,
            model: 27,
            turbo: 0,
            value: 30,
            pad: 0,
            mass: 20,
            front_drive_bias: 0.5,
            front_mass_bias: 0.4,
            brake_friction: 2,
            turn_in: 0.45,
            turn_ratio: 0.6,
            rear_end_stability: 1.15,
            handbrake_slide_value: 0.2,
            thrust: 0.16,
            max_speed: 0.227,
            anti_strength: 1,
            skid_threshhold: 0.07,
            gear1_multiplier: 0.5,
            gear2_multiplier: 0.65,
            gear3_multiplier: 1,
            gear2_speed: 0.08,
            gear3_speed: 0.142,
            meta: { w: 58, h: 88 }
        },
        'Dementia Limousine': {
            model_corrected: 22,
            model: 28,
            turbo: 0,
            value: 50,
            pad: 0,
            mass: 16,
            front_drive_bias: 0.5,
            front_mass_bias: 0.5,
            brake_friction: 2,
            turn_in: 0.125,
            turn_ratio: 0.5,
            rear_end_stability: 1.2,
            handbrake_slide_value: 0.2,
            thrust: 0.15,
            max_speed: 0.235,
            anti_strength: 1,
            skid_threshhold: 0.085,
            gear1_multiplier: 0.55,
            gear2_multiplier: 0.7,
            gear3_multiplier: 1,
            gear2_speed: 0.111,
            gear3_speed: 0.173,
            meta: { w: 48, h: 78 }
        },
        'Dementia': {
            model_corrected: 23,
            model: 29,
            turbo: 0,
            value: 10,
            pad: 0,
            mass: 6.3,
            front_drive_bias: 1,
            front_mass_bias: 0.45,
            brake_friction: 1.265,
            turn_in: 0.3,
            turn_ratio: 0.175,
            rear_end_stability: 1.5,
            handbrake_slide_value: 0.65,
            thrust: 0.095,
            max_speed: 0.235,
            anti_strength: 1,
            skid_threshhold: 0.05,
            gear1_multiplier: 0.55,
            gear2_multiplier: 0.625,
            gear3_multiplier: 1,
            gear2_speed: 0.125,
            gear3_speed: 0.152,
            meta: { w: 50, h: 46 }
        },
        'Land Roamer': {
            model_corrected: 24,
            model: 30,
            turbo: 0,
            value: 5,
            pad: 0,
            mass: 12,
            front_drive_bias: 0.5,
            front_mass_bias: 0.6,
            brake_friction: 1.75,
            turn_in: 0.55,
            turn_ratio: 0.35,
            rear_end_stability: 1.3,
            handbrake_slide_value: 0.175,
            thrust: 0.13,
            max_speed: 0.24,
            anti_strength: 1,
            skid_threshhold: 0.115,
            gear1_multiplier: 0.55,
            gear2_multiplier: 0.6,
            gear3_multiplier: 1,
            gear2_speed: 0.12,
            gear3_speed: 0.152,
            meta: { w: 42, h: 48 }
        },
        'Jefferson': {
            model_corrected: 25,
            model: 31,
            turbo: 1,
            value: 50,
            pad: 0,
            mass: 16,
            front_drive_bias: 1,
            front_mass_bias: 0.75,
            brake_friction: 2,
            turn_in: 0.65,
            turn_ratio: 0.45,
            rear_end_stability: 0.9,
            handbrake_slide_value: 0.2,
            thrust: 0.15,
            max_speed: 0.4,
            anti_strength: 1,
            skid_threshhold: 0.115,
            gear1_multiplier: 0.55,
            gear2_multiplier: 0.7,
            gear3_multiplier: 1,
            gear2_speed: 0.2,
            gear3_speed: 0.3,
            meta: { w: 46, h: 62 }
        },
        'Stretch Limousine': {
            model_corrected: 27,
            model: 32,
            turbo: 0,
            value: 50,
            pad: 0,
            mass: 24,
            front_drive_bias: 0.5,
            front_mass_bias: 0.5,
            brake_friction: 2,
            turn_in: 0.25,
            turn_ratio: 0.65,
            rear_end_stability: 0.8,
            handbrake_slide_value: 0.2,
            thrust: 0.21,
            max_speed: 0.275,
            anti_strength: 0.75,
            skid_threshhold: 0.085,
            gear1_multiplier: 0.55,
            gear2_multiplier: 0.8,
            gear3_multiplier: 1,
            gear2_speed: 0.12,
            gear3_speed: 0.215,
            meta: { w: 60, h: 112 }
        },
        'Sports Limousine': {
            model_corrected: 28,
            model: 33,
            turbo: 0,
            value: 50,
            pad: 0,
            mass: 24,
            front_drive_bias: 1,
            front_mass_bias: 0.5,
            brake_friction: 2,
            turn_in: 0.2,
            turn_ratio: 0.6,
            rear_end_stability: 0.75,
            handbrake_slide_value: 0.2,
            thrust: 0.22,
            max_speed: 0.295,
            anti_strength: 0.75,
            skid_threshhold: 0.085,
            gear1_multiplier: 0.55,
            gear2_multiplier: 0.8,
            gear3_multiplier: 1,
            gear2_speed: 0.135,
            gear3_speed: 0.23,
            meta: { w: 56, h: 110 }
        },
        'Medicar': {
            model_corrected: 29,
            model: 34,
            turbo: 0,
            value: 50,
            pad: 0,
            mass: 20,
            front_drive_bias: 0.5,
            front_mass_bias: 0.475,
            brake_friction: 2.75,
            turn_in: 0.25,
            turn_ratio: 0.5,
            rear_end_stability: 0.7,
            handbrake_slide_value: 0.275,
            thrust: 0.231,
            max_speed: 0.338,
            anti_strength: 1,
            skid_threshhold: 0.1,
            gear1_multiplier: 0.55,
            gear2_multiplier: 0.7,
            gear3_multiplier: 1,
            gear2_speed: 0.135,
            gear3_speed: 0.237,
            meta: { w: 62, h: 114 }
        },
        'Benson': {
            model_corrected: 30,
            model: 35,
            turbo: 1,
            value: 60,
            pad: 0,
            mass: 15.5,
            front_drive_bias: 0.5,
            front_mass_bias: 0.35,
            brake_friction: 2,
            turn_in: 0.25,
            turn_ratio: 0.4,
            rear_end_stability: 1.9,
            handbrake_slide_value: 0.35,
            thrust: 0.14,
            max_speed: 0.35,
            anti_strength: 1,
            skid_threshhold: 0.105,
            gear1_multiplier: 0.55,
            gear2_multiplier: 0.7,
            gear3_multiplier: 1,
            gear2_speed: 0.165,
            gear3_speed: 0.251,
            meta: { w: 38, h: 64 }
        },
        'Schmidt': {
            model_corrected: 31,
            model: 36,
            turbo: 0,
            value: 50,
            pad: 0,
            mass: 8,
            front_drive_bias: 0.5,
            front_mass_bias: 0.3,
            brake_friction: 2,
            turn_in: 0.55,
            turn_ratio: 0.25,
            rear_end_stability: 2,
            handbrake_slide_value: 0.15,
            thrust: 0.09,
            max_speed: 0.2,
            anti_strength: 1.25,
            skid_threshhold: 0.03,
            gear1_multiplier: 0.6,
            gear2_multiplier: 0.8,
            gear3_multiplier: 1,
            gear2_speed: 0.1,
            gear3_speed: 0.15,
            meta: { w: 38, h: 56 }
        },
        'Miara': {
            model_corrected: 32,
            model: 37,
            turbo: 0,
            value: 50,
            pad: 0,
            mass: 14.5,
            front_drive_bias: 1,
            front_mass_bias: 0.65,
            brake_friction: 2,
            turn_in: 0.25,
            turn_ratio: 0.4,
            rear_end_stability: 1.25,
            handbrake_slide_value: 0.15,
            thrust: 0.195,
            max_speed: 0.35,
            anti_strength: 1,
            skid_threshhold: 0.12,
            gear1_multiplier: 0.55,
            gear2_multiplier: 0.75,
            gear3_multiplier: 1,
            gear2_speed: 0.145,
            gear3_speed: 0.245,
            meta: { w: 62, h: 64 }
        },
        'Big Bug': {
            model_corrected: 33,
            model: 38,
            turbo: 0,
            value: 30,
            pad: 0,
            mass: 22,
            front_drive_bias: 0.5,
            front_mass_bias: 0.4,
            brake_friction: 2,
            turn_in: 0.1,
            turn_ratio: 0.6,
            rear_end_stability: 1.5,
            handbrake_slide_value: 0.2,
            thrust: 0.2,
            max_speed: 0.24,
            anti_strength: 1,
            skid_threshhold: 0.085,
            gear1_multiplier: 0.55,
            gear2_multiplier: 0.75,
            gear3_multiplier: 1,
            gear2_speed: 0.104,
            gear3_speed: 0.175,
            meta: { w: 58, h: 58 }
        },
        'Morton': {
            model_corrected: 34,
            model: 39,
            turbo: 0,
            value: 50,
            pad: 0,
            mass: 16.5,
            front_drive_bias: 0.5,
            front_mass_bias: 0.6,
            brake_friction: 2,
            turn_in: 0.45,
            turn_ratio: 0.55,
            rear_end_stability: 0.9,
            handbrake_slide_value: 0.2,
            thrust: 0.152,
            max_speed: 0.265,
            anti_strength: 1,
            skid_threshhold: 0.135,
            gear1_multiplier: 0.65,
            gear2_multiplier: 0.75,
            gear3_multiplier: 1,
            gear2_speed: 0.125,
            gear3_speed: 0.19,
            meta: { w: 48, h: 60 }
        },
        'Maurice': {
            model_corrected: 35,
            model: 40,
            turbo: 0,
            value: 50,
            pad: 0,
            mass: 13,
            front_drive_bias: 1,
            front_mass_bias: 0.4,
            brake_friction: 1.75,
            turn_in: 0.25,
            turn_ratio: 0.35,
            rear_end_stability: 1.25,
            handbrake_slide_value: 0.25,
            thrust: 0.14,
            max_speed: 0.26,
            anti_strength: 1,
            skid_threshhold: 0.085,
            gear1_multiplier: 0.55,
            gear2_multiplier: 0.68,
            gear3_multiplier: 1,
            gear2_speed: 0.12,
            gear3_speed: 0.175,
            meta: { w: 56, h: 58 }
        },
        'Pickup': {
            model_corrected: 36,
            model: 41,
            turbo: 0,
            value: 15,
            pad: 0,
            mass: 16,
            front_drive_bias: 0.5,
            front_mass_bias: 0.6,
            brake_friction: 2,
            turn_in: 0.5,
            turn_ratio: 0.45,
            rear_end_stability: 0.5,
            handbrake_slide_value: 0.2,
            thrust: 0.135,
            max_speed: 0.255,
            anti_strength: 1,
            skid_threshhold: 0.08,
            gear1_multiplier: 0.55,
            gear2_multiplier: 0.8,
            gear3_multiplier: 1,
            gear2_speed: 0.12,
            gear3_speed: 0.19,
            meta: { w: 58, h: 64 }
        },
        'A-Type': {
            model_corrected: 37,
            model: 42,
            turbo: 1,
            value: 50,
            pad: 0,
            mass: 15,
            front_drive_bias: 1,
            front_mass_bias: 0.6,
            brake_friction: 2,
            turn_in: 0.45,
            turn_ratio: 0.45,
            rear_end_stability: 1,
            handbrake_slide_value: 0.5,
            thrust: 0.126,
            max_speed: 0.385,
            anti_strength: 1,
            skid_threshhold: 0.118,
            gear1_multiplier: 0.55,
            gear2_multiplier: 0.75,
            gear3_multiplier: 1,
            gear2_speed: 0.175,
            gear3_speed: 0.272,
            meta: { w: 60, h: 64 }
        },
        'Arachnid': {
            model_corrected: 38,
            model: 44,
            turbo: 0,
            value: 50,
            pad: 0,
            mass: 14.5,
            front_drive_bias: 1,
            front_mass_bias: 0.5,
            brake_friction: 1.75,
            turn_in: 0.145,
            turn_ratio: 0.45,
            rear_end_stability: 1,
            handbrake_slide_value: 0.18,
            thrust: 0.152,
            max_speed: 0.285,
            anti_strength: 1,
            skid_threshhold: 0.085,
            gear1_multiplier: 0.55,
            gear2_multiplier: 0.725,
            gear3_multiplier: 1,
            gear2_speed: 0.135,
            gear3_speed: 0.2,
            meta: { w: 54, h: 62 }
        },
        'Spritzer': {
            model_corrected: 39,
            model: 45,
            turbo: 0,
            value: 50,
            pad: 0,
            mass: 14,
            front_drive_bias: 0.5,
            front_mass_bias: 0.55,
            brake_friction: 2.5,
            turn_in: 0.145,
            turn_ratio: 0.4,
            rear_end_stability: 1,
            handbrake_slide_value: 0.55,
            thrust: 0.125,
            max_speed: 0.235,
            anti_strength: 1,
            skid_threshhold: 0.065,
            gear1_multiplier: 0.65,
            gear2_multiplier: 0.7,
            gear3_multiplier: 1,
            gear2_speed: 0.125,
            gear3_speed: 0.162,
            meta: { w: 60, h: 56 }
        },
        'Stinger': {
            model_corrected: 40,
            model: 46,
            turbo: 1,
            value: 50,
            pad: 0,
            mass: 15,
            front_drive_bias: 0.6,
            front_mass_bias: 0.6,
            brake_friction: 3,
            turn_in: 0.1,
            turn_ratio: 0.65,
            rear_end_stability: 1,
            handbrake_slide_value: 0.3,
            thrust: 0.14,
            max_speed: 0.401,
            anti_strength: 1,
            skid_threshhold: 0.115,
            gear1_multiplier: 0.55,
            gear2_multiplier: 0.7,
            gear3_multiplier: 1,
            gear2_speed: 0.174,
            gear3_speed: 0.285,
            meta: { w: 52, h: 62 }
        },
        'Meteor': {
            model_corrected: 41,
            model: 47,
            turbo: 0,
            value: 50,
            pad: 0,
            mass: 13.5,
            front_drive_bias: 0.5,
            front_mass_bias: 0.6,
            brake_friction: 2,
            turn_in: 0.35,
            turn_ratio: 0.5,
            rear_end_stability: 0.9,
            handbrake_slide_value: 0.2,
            thrust: 0.16,
            max_speed: 0.32,
            anti_strength: 1,
            skid_threshhold: 0.115,
            gear1_multiplier: 0.7,
            gear2_multiplier: 0.85,
            gear3_multiplier: 1,
            gear2_speed: 0.185,
            gear3_speed: 0.265,
            meta: { w: 60, h: 64 }
        },
        'Meteor Turbo': {
            model_corrected: 42,
            model: 48,
            turbo: 1,
            value: 60,
            pad: 0,
            mass: 14.5,
            front_drive_bias: 0.5,
            front_mass_bias: 0.6,
            brake_friction: 1.75,
            turn_in: 0.45,
            turn_ratio: 0.4,
            rear_end_stability: 1.3,
            handbrake_slide_value: 0.4,
            thrust: 0.175,
            max_speed: 0.42,
            anti_strength: 1,
            skid_threshhold: 0.115,
            gear1_multiplier: 0.55,
            gear2_multiplier: 0.725,
            gear3_multiplier: 1,
            gear2_speed: 0.235,
            gear3_speed: 0.36,
            meta: { w: 60, h: 64 }
        },
        'Hachura': {
            model_corrected: 43,
            model: 49,
            turbo: 0,
            value: 50,
            pad: 0,
            mass: 14,
            front_drive_bias: 0.75,
            front_mass_bias: 0.6,
            brake_friction: 2,
            turn_in: 0.35,
            turn_ratio: 0.55,
            rear_end_stability: 0.9,
            handbrake_slide_value: 0.2,
            thrust: 0.225,
            max_speed: 0.4,
            anti_strength: 1,
            skid_threshhold: 0.115,
            gear1_multiplier: 0.5,
            gear2_multiplier: 0.72,
            gear3_multiplier: 1,
            gear2_speed: 0.185,
            gear3_speed: 0.3,
            meta: { w: 64, h: 64 }
        },
        'B-Type': {
            model_corrected: 44,
            model: 50,
            turbo: 1,
            value: 50,
            pad: 0,
            mass: 15,
            front_drive_bias: 0.6,
            front_mass_bias: 0.5,
            brake_friction: 2,
            turn_in: 0.1,
            turn_ratio: 0.5,
            rear_end_stability: 0.85,
            handbrake_slide_value: 0.2,
            thrust: 0.14,
            max_speed: 0.401,
            anti_strength: 1,
            skid_threshhold: 0.125,
            gear1_multiplier: 0.55,
            gear2_multiplier: 0.7,
            gear3_multiplier: 1,
            gear2_speed: 0.174,
            gear3_speed: 0.29,
            meta: { w: 56, h: 64 }
        },
        'Taxi Xpress': {
            model_corrected: 45,
            model: 51,
            turbo: 0,
            value: 50,
            pad: 0,
            mass: 15,
            front_drive_bias: 1,
            front_mass_bias: 0.6,
            brake_friction: 2,
            turn_in: 0.4,
            turn_ratio: 0.4,
            rear_end_stability: 0.7,
            handbrake_slide_value: 0.2,
            thrust: 0.145,
            max_speed: 0.27,
            anti_strength: 1,
            skid_threshhold: 0.115,
            gear1_multiplier: 0.65,
            gear2_multiplier: 0.8,
            gear3_multiplier: 1,
            gear2_speed: 0.135,
            gear3_speed: 0.21,
            meta: { w: 56, h: 64 }
        },
        'SWAT Van': {
            model_corrected: 46,
            model: 52,
            turbo: 0,
            value: 90,
            pad: 0,
            mass: 22,
            front_drive_bias: 0.5,
            front_mass_bias: 0.6,
            brake_friction: 2,
            turn_in: 0.25,
            turn_ratio: 0.8,
            rear_end_stability: 1.4,
            handbrake_slide_value: 0.3,
            thrust: 0.175,
            max_speed: 0.225,
            anti_strength: 0.5,
            skid_threshhold: 0.13,
            gear1_multiplier: 0.65,
            gear2_multiplier: 0.75,
            gear3_multiplier: 1,
            gear2_speed: 0.115,
            gear3_speed: 0.166,
            meta: { w: 64, h: 98 }
        },
        'Michelli Roadster': {
            model_corrected: 47,
            model: 53,
            turbo: 0,
            value: 50,
            pad: 0,
            mass: 13,
            front_drive_bias: 1,
            front_mass_bias: 0.8,
            brake_friction: 1,
            turn_in: 0.175,
            turn_ratio: 0.5,
            rear_end_stability: 0.75,
            handbrake_slide_value: 0.35,
            thrust: 0.175,
            max_speed: 0.388,
            anti_strength: 1,
            skid_threshhold: 0.1,
            gear1_multiplier: 0.65,
            gear2_multiplier: 0.8,
            gear3_multiplier: 1,
            gear2_speed: 0.165,
            gear3_speed: 0.275,
            meta: { w: 50, h: 64 }
        },
        'Tank': {
            model_corrected: 48,
            model: 54,
            turbo: 0,
            value: 95,
            pad: 0,
            mass: 45,
            front_drive_bias: 0.5,
            front_mass_bias: 0.5,
            brake_friction: 4,
            turn_in: 0.25,
            turn_ratio: 0.75,
            rear_end_stability: 4,
            handbrake_slide_value: 0,
            thrust: 0.29,
            max_speed: 0.2,
            anti_strength: 0.25,
            skid_threshhold: 0.5,
            gear1_multiplier: 0.53,
            gear2_multiplier: 0.6,
            gear3_multiplier: 1,
            gear2_speed: 0.05,
            gear3_speed: 0.06,
            meta: { w: 46, h: 82 }
        },
        'Tanker': {
            model: 55,
            turbo: 0,
            value: 80,
            pad: 0,
            mass: 30,
            front_drive_bias: 0,
            front_mass_bias: 0.5,
            brake_friction: 0.9,
            turn_in: 0.1,
            turn_ratio: 0.8,
            rear_end_stability: 2,
            handbrake_slide_value: 0.2,
            thrust: 0,
            max_speed: 0.3,
            anti_strength: 1,
            skid_threshhold: 0.139,
            gear1_multiplier: 0.6,
            gear2_multiplier: 0.8,
            gear3_multiplier: 1,
            gear2_speed: 0.152,
            gear3_speed: 0.228,
            meta: { w: 44, h: 128 }
        },
        'Taxi': {
            model_corrected: 50,
            model: 56,
            turbo: 0,
            value: 50,
            pad: 0,
            mass: 14.5,
            front_drive_bias: 1,
            front_mass_bias: 0.55,
            brake_friction: 2.5,
            turn_in: 0.15,
            turn_ratio: 0.45,
            rear_end_stability: 1,
            handbrake_slide_value: 0.2,
            thrust: 0.13,
            max_speed: 0.219,
            anti_strength: 1,
            skid_threshhold: 0.065,
            gear1_multiplier: 0.6,
            gear2_multiplier: 0.75,
            gear3_multiplier: 1,
            gear2_speed: 0.125,
            gear3_speed: 0.175,
            meta: { w: 60, h: 64 }
        },
        'T-Rex': {
            model_corrected: 51,
            model: 57,
            turbo: 0,
            value: 50,
            pad: 0,
            mass: 15.5,
            front_drive_bias: 1,
            front_mass_bias: 0.55,
            brake_friction: 2,
            turn_in: 0.35,
            turn_ratio: 0.35,
            rear_end_stability: 0.95,
            handbrake_slide_value: 0.35,
            thrust: 0.225,
            max_speed: 0.405,
            anti_strength: 1,
            skid_threshhold: 0.115,
            gear1_multiplier: 0.55,
            gear2_multiplier: 0.65,
            gear3_multiplier: 1,
            gear2_speed: 0.175,
            gear3_speed: 0.255,
            meta: { w: 60, h: 64 }
        },
        'Tow Truck': {
            model_corrected: 52,
            model: 58,
            turbo: 0,
            value: 30,
            pad: 0,
            mass: 22,
            front_drive_bias: 0.5,
            front_mass_bias: 0.8,
            brake_friction: 2.5,
            turn_in: 0.5,
            turn_ratio: 0.8,
            rear_end_stability: 1,
            handbrake_slide_value: 0.85,
            thrust: 0.15,
            max_speed: 0.2,
            anti_strength: 1,
            skid_threshhold: 0.13,
            gear1_multiplier: 0.55,
            gear2_multiplier: 0.65,
            gear3_multiplier: 1,
            gear2_speed: 0.1,
            gear3_speed: 0.133,
            meta: { w: 58, h: 80 }
        },
        'Train': {
            model: 59,
            turbo: 0,
            value: 200,
            pad: 0,
            mass: 10,
            front_drive_bias: 0,
            front_mass_bias: 0.5,
            brake_friction: 0.9,
            turn_in: 0.1,
            turn_ratio: 0.8,
            rear_end_stability: 2,
            handbrake_slide_value: 0.2,
            thrust: 0.143,
            max_speed: 0.399,
            anti_strength: 1,
            skid_threshhold: 0.139,
            gear1_multiplier: 0.6,
            gear2_multiplier: 0.8,
            gear3_multiplier: 1,
            gear2_speed: 0.152,
            gear3_speed: 0.228,
            meta: { w: 42, h: 128 }
        },
        'Train Cab': {
            model: 60,
            turbo: 0,
            value: 200,
            pad: 0,
            mass: 10,
            front_drive_bias: 0,
            front_mass_bias: 0.5,
            brake_friction: 0.9,
            turn_in: 0.1,
            turn_ratio: 0.8,
            rear_end_stability: 2,
            handbrake_slide_value: 0.2,
            thrust: 0.143,
            max_speed: 0.95,
            anti_strength: 1,
            skid_threshhold: 0.139,
            gear1_multiplier: 0.6,
            gear2_multiplier: 0.8,
            gear3_multiplier: 1,
            gear2_speed: 0.152,
            gear3_speed: 0.228,
            meta: { w: 40, h: 128 }
        },
        'Train FB': {
            model: 61,
            turbo: 0,
            value: 200,
            pad: 0,
            mass: 10,
            front_drive_bias: 0,
            front_mass_bias: 0.5,
            brake_friction: 0.9,
            turn_in: 0.1,
            turn_ratio: 0.8,
            rear_end_stability: 2,
            handbrake_slide_value: 0.2,
            thrust: 0.143,
            max_speed: 0.95,
            anti_strength: 1,
            skid_threshhold: 0.139,
            gear1_multiplier: 0.6,
            gear2_multiplier: 0.8,
            gear3_multiplier: 1,
            gear2_speed: 0.152,
            gear3_speed: 0.228,
            meta: { w: 58, h: 74 }
        },
        'Trance-Am': {
            model_corrected: 56,
            model: 62,
            turbo: 0,
            value: 50,
            pad: 0,
            mass: 14,
            front_drive_bias: 1,
            front_mass_bias: 0.5,
            brake_friction: 3,
            turn_in: 0.1,
            turn_ratio: 0.4,
            rear_end_stability: 0.85,
            handbrake_slide_value: 0.3,
            thrust: 0.165,
            max_speed: 0.34,
            anti_strength: 1,
            skid_threshhold: 0.09,
            gear1_multiplier: 0.65,
            gear2_multiplier: 0.8,
            gear3_multiplier: 1,
            gear2_speed: 0.152,
            gear3_speed: 0.25,
            meta: { w: 54, h: 64 }
        },
        'Truck Cab': {
            model_corrected: 57,
            model: 63,
            turbo: 0,
            value: 40,
            pad: 0,
            mass: 19,
            front_drive_bias: 1,
            front_mass_bias: 0.75,
            brake_friction: 1.75,
            turn_in: 0.75,
            turn_ratio: 0.7,
            rear_end_stability: 3,
            handbrake_slide_value: 0.1,
            thrust: 0.175,
            max_speed: 0.2,
            anti_strength: 1,
            skid_threshhold: 0.139,
            gear1_multiplier: 0.45,
            gear2_multiplier: 0.6,
            gear3_multiplier: 1,
            gear2_speed: 0.075,
            gear3_speed: 0.108,
            meta: { w: 64, h: 64 }
        },
        'Truck Cab SX': {
            model_corrected: 58,
            model: 64,
            turbo: 0,
            value: 40,
            pad: 0,
            mass: 19,
            front_drive_bias: 0.487,
            front_mass_bias: 0.189,
            brake_friction: 2,
            turn_in: 0,
            turn_ratio: 0.527,
            rear_end_stability: 2,
            handbrake_slide_value: 0.2,
            thrust: 0.3,
            max_speed: 0.2,
            anti_strength: 1,
            skid_threshhold: 0.139,
            gear1_multiplier: 0.6,
            gear2_multiplier: 0.8,
            gear3_multiplier: 1,
            gear2_speed: 0.075,
            gear3_speed: 0.108,
            meta: { w: 64, h: 64 }
        },
        'Container': {
            model_corrected: 59,
            model: 65,
            turbo: 0,
            value: 60,
            pad: 0,
            mass: 30,
            front_drive_bias: 0,
            front_mass_bias: 0.5,
            brake_friction: 0.9,
            turn_in: 0.1,
            turn_ratio: 0.8,
            rear_end_stability: 2,
            handbrake_slide_value: 0.2,
            thrust: 0,
            max_speed: 0.2,
            anti_strength: 1,
            skid_threshhold: 0.139,
            gear1_multiplier: 0.6,
            gear2_multiplier: 0.8,
            gear3_multiplier: 1,
            gear2_speed: 0,
            gear3_speed: 0,
            meta: { w: 42, h: 128 }
        },
        'Transporter': {
            model_corrected: 60,
            model: 66,
            turbo: 0,
            value: 70,
            pad: 0,
            mass: 30,
            front_drive_bias: 0,
            front_mass_bias: 0.5,
            brake_friction: 0.9,
            turn_in: 0.1,
            turn_ratio: 0.8,
            rear_end_stability: 2,
            handbrake_slide_value: 0.2,
            thrust: 0,
            max_speed: 0.2,
            anti_strength: 1,
            skid_threshhold: 0.139,
            gear1_multiplier: 0.6,
            gear2_multiplier: 0.8,
            gear3_multiplier: 1,
            gear2_speed: 0,
            gear3_speed: 0,
            meta: { w: 40, h: 128 }
        },
        'TV Van': {
            model_corrected: 61,
            model: 67,
            turbo: 0,
            value: 20,
            pad: 0,
            mass: 19,
            front_drive_bias: 0.5,
            front_mass_bias: 0.8,
            brake_friction: 2.5,
            turn_in: 0.5,
            turn_ratio: 0.8,
            rear_end_stability: 1,
            handbrake_slide_value: 0.85,
            thrust: 0.15,
            max_speed: 0.205,
            anti_strength: 1,
            skid_threshhold: 0.13,
            gear1_multiplier: 0.55,
            gear2_multiplier: 0.65,
            gear3_multiplier: 1,
            gear2_speed: 0.1,
            gear3_speed: 0.14,
            meta: { w: 58, h: 74 }
        },
        'Van': {
            model: 61,
            turbo: 0,
            value: 20,
            pad: 0,
            mass: 19,
            front_drive_bias: 0.5,
            front_mass_bias: 0.8,
            brake_friction: 2.5,
            turn_in: 0.5,
            turn_ratio: 0.8,
            rear_end_stability: 1,
            handbrake_slide_value: 0.85,
            thrust: 0.15,
            max_speed: 0.205,
            anti_strength: 1,
            skid_threshhold: 0.13,
            gear1_multiplier: 0.55,
            gear2_multiplier: 0.65,
            gear3_multiplier: 1,
            gear2_speed: 0.1,
            gear3_speed: 0.14,
            meta: { w: 58, h: 74 }
        },
        'U-Jerk Truck': {
            model_corrected: 62,
            model: 69,
            turbo: 0,
            value: 20,
            pad: 0,
            mass: 16,
            front_drive_bias: 0.5,
            front_mass_bias: 0.75,
            brake_friction: 2,
            turn_in: 0.75,
            turn_ratio: 0.5,
            rear_end_stability: 0.25,
            handbrake_slide_value: 0.2,
            thrust: 0.11,
            max_speed: 0.225,
            anti_strength: 1,
            skid_threshhold: 0.11,
            gear1_multiplier: 0.55,
            gear2_multiplier: 0.75,
            gear3_multiplier: 1,
            gear2_speed: 0.085,
            gear3_speed: 0.15,
            meta: { w: 54, h: 56 }
        },
        'Z-Type': {
            model_corrected: 44,
            model: 70,
            turbo: 1,
            value: 50,
            pad: 0,
            mass: 15,
            front_drive_bias: 1,
            front_mass_bias: 0.5,
            brake_friction: 2,
            turn_in: 0.4,
            turn_ratio: 0.35,
            rear_end_stability: 1.175,
            handbrake_slide_value: 0.4,
            thrust: 0.145,
            max_speed: 0.405,
            anti_strength: 1,
            skid_threshhold: 0.12,
            gear1_multiplier: 0.6,
            gear2_multiplier: 0.7,
            gear3_multiplier: 1,
            gear2_speed: 0.19,
            gear3_speed: 0.284,
            meta: { w: 56, h: 64 }
        },
        'Rumbler': {
            model_corrected: 64,
            model: 71,
            turbo: 1,
            value: 50,
            pad: 0,
            mass: 15,
            front_drive_bias: 0.5,
            front_mass_bias: 0.375,
            brake_friction: 3.5,
            turn_in: 0.25,
            turn_ratio: 0.65,
            rear_end_stability: 1.4,
            handbrake_slide_value: 0.35,
            thrust: 0.14,
            max_speed: 0.401,
            anti_strength: 1,
            skid_threshhold: 0.115,
            gear1_multiplier: 0.55,
            gear2_multiplier: 0.7,
            gear3_multiplier: 1,
            gear2_speed: 0.175,
            gear3_speed: 0.27,
            meta: { w: 56, h: 64 }
        },
        /*'Wreck 0': {
model: 72,
turbo: 0,
value: 0,
pad: 0,
mass: 10,
front drive bias: 0,
front mass bias: 0.5,
brake friction: 0.9,
turn in: 0.1,
turn ratio: 0.8,
rear end stability: 2,
handbrake slide value: 0.2,
thrust: 0,
max_speed: 0.95,
anti strength: 1,
skid threshhold: 0.139,
gear1 multiplier: 0.6,
gear2 multiplier: 0.8,
gear3 multiplier: 1,
gear2 speed: 0.152,
gear3 speed: 0.228,
image_width: 36,
image_height: 112
        },
        'Wreck 1': {
model: 73,
turbo: 0,
value: 0,
pad: 0,
mass: 10,
front drive bias: 0,
front mass bias: 0.5,
brake friction: 0.9,
turn in: 0.1,
turn ratio: 0.8,
rear end stability: 2,
handbrake slide value: 0.2,
thrust: 0,
max_speed: 0.95,
anti strength: 1,
skid threshhold: 0.139,
gear1 multiplier: 0.6,
gear2 multiplier: 0.8,
gear3 multiplier: 1,
gear2 speed: 0.152,
gear3 speed: 0.228,
image_width: 40,
image_height: 74
        },
        'Wreck 2': {
model: 74,
turbo: 0,
value: 0,
pad: 0,
mass: 10,
front drive bias: 0,
front mass bias: 0.5,
brake friction: 0.9,
turn in: 0.1,
turn ratio: 0.8,
rear end stability: 2,
handbrake slide value: 0.2,
thrust: 0,
max_speed: 0.95,
anti strength: 1,
skid threshhold: 0.139,
gear1 multiplier: 0.6,
gear2 multiplier: 0.8,
gear3 multiplier: 1,
gear2 speed: 0.152,
gear3 speed: 0.228,
image_width: 46,
image_height: 82
        },
        'Wreck 3': {
model: 75,
turbo: 0,
value: 0,
pad: 0,
mass: 10,
front drive bias: 0,
front mass bias: 0.5,
brake friction: 0.9,
turn in: 0.1,
turn ratio: 0.8,
rear end stability: 2,
handbrake slide value: 0.2,
thrust: 0,
max_speed: 0.95,
anti strength: 1,
skid threshhold: 0.139,
gear1 multiplier: 0.6,
gear2 multiplier: 0.8,
gear3 multiplier: 1,
gear2 speed: 0.152,
gear3 speed: 0.228,
image_width: 52,
image_height: 64
        },
        'Wreck 4': {
model: 76,
turbo: 0,
value: 0,
pad: 0,
mass: 10,
front drive bias: 0,
front mass bias: 0.5,
brake friction: 0.9,
turn in: 0.1,
turn ratio: 0.8,
rear end stability: 2,
handbrake slide value: 0.2,
thrust: 0,
max_speed: 0.95,
anti strength: 1,
skid threshhold: 0.139,
gear1 multiplier: 0.6,
gear2 multiplier: 0.8,
gear3 multiplier: 1,
gear2 speed: 0.152,
gear3 speed: 0.228,
image_width: 50,
image_height: 64
        },
        'Wreck 5': {
model: 77,
turbo: 0,
value: 0,
pad: 0,
mass: 10,
front drive bias: 0,
front mass bias: 0.5,
brake friction: 0.9,
turn in: 0.1,
turn ratio: 0.8,
rear end stability: 2,
handbrake slide value: 0.2,
thrust: 0,
max_speed: 0.95,
anti strength: 1,
skid threshhold: 0.139,
gear1 multiplier: 0.6,
gear2 multiplier: 0.8,
gear3 multiplier: 1,
gear2 speed: 0.152,
gear3 speed: 0.228,
image_width: 64,
image_height: 64
        },
        'Wreck 6': {
model: 78,
turbo: 0,
value: 0,
pad: 0,
mass: 10,
front drive bias: 0,
front mass bias: 0.5,
brake friction: 0.9,
turn in: 0.1,
turn ratio: 0.8,
rear end stability: 2,
handbrake slide value: 0.2,
thrust: 0,
max_speed: 0.95,
anti strength: 1,
skid threshhold: 0.139,
gear1 multiplier: 0.6,
gear2 multiplier: 0.8,
gear3 multiplier: 1,
gear2 speed: 0.152,
gear3 speed: 0.228,
image_width: 64,
image_height: 64
        },
        'Wreck 7': {
model: 79,
turbo: 0,
value: 0,
pad: 0,
mass: 10,
front drive bias: 0,
front mass bias: 0.5,
brake friction: 0.9,
turn in: 0.1,
turn ratio: 0.8,
rear end stability: 2,
handbrake slide value: 0.2,
thrust: 0,
max_speed: 0.95,
anti strength: 1,
skid threshhold: 0.139,
gear1 multiplier: 0.6,
gear2 multiplier: 0.8,
gear3 multiplier: 1,
gear2 speed: 0.152,
gear3 speed: 0.228,
image_width: 64,
image_height: 64
        },
        'Wreck 8': {
model: 80,
turbo: 0,
value: 0,
pad: 0,
mass: 10,
front drive bias: 0,
front mass bias: 0.5,
brake friction: 0.9,
turn in: 0.1,
turn ratio: 0.8,
rear end stability: 2,
handbrake slide value: 0.2,
thrust: 0,
max_speed: 0.95,
anti strength: 1,
skid threshhold: 0.139,
gear1 multiplier: 0.6,
gear2 multiplier: 0.8,
gear3 multiplier: 1,
gear2 speed: 0.152,
gear3 speed: 0.228,
image_width: 64,
image_height: 64
        },
        'Wreck 9': {
model: 81,
turbo: 0,
value: 0,
pad: 0,
mass: 10,
front drive bias: 0,
front mass bias: 0.5,
brake friction: 0.9,
turn in: 0.1,
turn ratio: 0.8,
rear end stability: 2,
handbrake slide value: 0.2,
thrust: 0,
max_speed: 0.95,
anti strength: 1,
skid threshhold: 0.139,
gear1 multiplier: 0.6,
gear2 multiplier: 0.8,
gear3 multiplier: 1,
gear2 speed: 0.152,
gear3 speed: 0.228,
image_width: 64,
image_height: 64
        },*/
        'Jagular XK': {
            model_corrected: 75,
            model: 82,
            turbo: 0,
            value: 50,
            pad: 0,
            mass: 14,
            front_drive_bias: 0.5,
            front_mass_bias: 0.5,
            brake_friction: 2,
            turn_in: 0.35,
            turn_ratio: 0.45,
            rear_end_stability: 1.4,
            handbrake_slide_value: 0.35,
            thrust: 0.185,
            max_speed: 0.33,
            anti_strength: 1,
            skid_threshhold: 0.105,
            gear1_multiplier: 0.65,
            gear2_multiplier: 0.8,
            gear3_multiplier: 1,
            gear2_speed: 0.18,
            gear3_speed: 0.255,
            meta: { w: 52, h: 64 }
        },
        'Furore GT': {
            model_corrected: 76,
            model: 83,
            turbo: 1,
            value: 50,
            pad: 0,
            mass: 14.104,
            front_drive_bias: 0.156,
            front_mass_bias: 0.61,
            brake_friction: 2.015,
            turn_in: 0.063,
            turn_ratio: 0.993,
            rear_end_stability: 0.85,
            handbrake_slide_value: 0.1,
            thrust: 0.142,
            max_speed: 0.416,
            anti_strength: 1,
            skid_threshhold: 0.142,
            gear1_multiplier: 0.626,
            gear2_multiplier: 0.797,
            gear3_multiplier: 1,
            gear2_speed: 0.235,
            gear3_speed: 0.35,
            meta: { w: 50, h: 64 }
        },
        'Special Agent Car': {
            model: 84,
            turbo: 0,
            value: 70,
            pad: 0,
            mass: 15,
            front_drive_bias: 1,
            front_mass_bias: 0.6,
            brake_friction: 2,
            turn_in: 0.155,
            turn_ratio: 0.45,
            rear_end_stability: 1.2,
            handbrake_slide_value: 0.35,
            thrust: 0.165,
            max_speed: 0.3,
            anti_strength: 0.8,
            skid_threshhold: 0.085,
            gear1_multiplier: 0.55,
            gear2_multiplier: 0.7,
            gear3_multiplier: 1,
            gear2_speed: 0.13,
            gear3_speed: 0.195,
            meta: { w: 64, h: 64 }
        },
        'Karma Bus': {
            model_corrected: 26,
            model: 86,
            turbo: 0,
            value: 30,
            pad: 0,
            mass: 22,
            front_drive_bias: 0.5,
            front_mass_bias: 0.4,
            brake_friction: 2,
            turn_in: 0.45,
            turn_ratio: 0.6,
            rear_end_stability: 1.15,
            handbrake_slide_value: 0.2,
            thrust: 0.165,
            max_speed: 0.275,
            anti_strength: 1,
            skid_threshhold: 0.07,
            gear1_multiplier: 0.55,
            gear2_multiplier: 0.75,
            gear3_multiplier: 1,
            gear2_speed: 0.115,
            gear3_speed: 0.165,
            meta: { w: 44, h: 100 }
        }
    };
})(EveryLineIsAPhysic || (EveryLineIsAPhysic = {}));
export default EveryLineIsAPhysic;
