export const parkedCarNames = [
    "Romero", "Wellard", "Aniston BD4",
    "Beamer",
    "Bug", "Bulwark", /*"Bus",*/ "Cop Car",
    "Minx", "Eddy", "Panto",
    "Shark", "GT-A1",
    /*"Hot Dog Van", "Ice-Cream Van", "Dementia Limousine",*/ "Dementia",
    "Land Roamer", "Jefferson",
    /*"Medicar",*/ "Benson", "Schmidt", "Miara",
    "Big Bug", "Morton", "Maurice", "Pickup",
    "A-Type", "Arachnid", "Spritzer", "Stinger",
    "Meteor", /*"Meteor Twoo?",*/ "Hachura", "B-Type",
    "Taxi Xpress", /*"SWAT Van",*/ "Michelli Roadster",
    "Taxi", "T-Rex",
    /*"Train", "Train Cab", "Train FB",*/ "Trance-Am",
    /*"Truck Cab", "Truck Cab SX", "Container", "Transporter",*/
    "TV Van", "Van", "U-Jerk Truck", "Z-Type",
    "Rumbler",
    "Jagular XK",
    "Furore GT", "Special Agent Car" /*, "Karma Bus",*/
];
export const carScriptCodes = {
    'Arachnid': 'SPIDER',
    'Armed Land Roamer': 'GUNJEEP',
    'A-Type': 'RTYPE',
    'Beamer': 'BMW',
    'Benson': 'MERC',
    'Box Truck': 'BOXTRUCK',
    'Big Bug': 'MONSTER',
    'B-Type': 'STYPE',
    'Bug': 'BUG',
    'Bus': 'BUS',
    'Bulwark': 'BUICK',
    'Container': 'TRUKCONT',
    'Cop Car': 'COPCAR',
    'Dementia': 'ISETTA',
    'Dementia Limousine': 'ISETLIMO',
    'Eddy': 'EDSEL',
    'Fire Truck': 'FIRETRUK',
    'Furore GT': 'ZCX5',
    'G4 Bank Van': 'BANKVAN',
    'Garbage Truck': 'GTRUCK',
    'GT-A1': 'GT24640',
    'Hachura': 'STRIPETB',
    'Hot Dog Van': 'HOTDOG',
    'Ice-Cream Van': 'ICECREAM',
    'Jagular XK': 'XK120',
    'Jefferson': 'JEFFREY',
    'Karma Bus': 'KRSNABUS',
    'Land Roamer': 'JEEP',
    'Maurice': 'MORRIS',
    'Medicar': 'MEDICAR',
    'Meteor': 'STRATOS',
    'Meteor Twoo?': 'STRATOSB',
    'Miara': 'MIURA',
    'Michelli Roadster': 'T2000GT',
    'Minx': 'DART',
    'Morton': 'MORGAN',
    'Pacifier': 'APC',
    'Panto': 'FIAT',
    'Pickup': 'PICKUP',
    'Romero': 'ALFA',
    'Rumbler': 'WBTWIN',
    'Schmidt': 'MESSER',
    'Shark': 'GRAHAM',
    'Special Agent Car': 'EDSELFBI',
    'Sports Limousine': 'LIMO2',
    'Spritzer': 'SPRITE',
    'Stinger': 'STINGRAY',
    'Stretch Limousine': 'LIMO',
    'SWAT Van': 'SWATVAN',
    'Tank': 'TANK',
    'Tanker': 'TANKER',
    'Taxi': 'TAXI',
    'Taxi Xpress': 'STYPECAB',
    'Tow Truck': 'TOWTRUCK',
    'Trance-Am': 'TRANCEAM',
    'Transporter': 'TRUKTRNS',
    'T-Rex': 'TBIRD',
    'Truck Cab': 'TRUKCAB1',
    'Truck Cab SX': 'TRUKCAB2',
    'TV Van': 'TVVAN',
    'U-Jerk Truck': 'VESPA',
    'Van': 'VAN',
    'Wellard': 'ALLARD',
    'Z-Type': 'VTYPE'
};
